// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shipherman/gophermart/ent/predicate"
	"github.com/shipherman/gophermart/ent/withdrawals"
)

// WithdrawalsDelete is the builder for deleting a Withdrawals entity.
type WithdrawalsDelete struct {
	config
	hooks    []Hook
	mutation *WithdrawalsMutation
}

// Where appends a list predicates to the WithdrawalsDelete builder.
func (wd *WithdrawalsDelete) Where(ps ...predicate.Withdrawals) *WithdrawalsDelete {
	wd.mutation.Where(ps...)
	return wd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (wd *WithdrawalsDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, wd.sqlExec, wd.mutation, wd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (wd *WithdrawalsDelete) ExecX(ctx context.Context) int {
	n, err := wd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (wd *WithdrawalsDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(withdrawals.Table, sqlgraph.NewFieldSpec(withdrawals.FieldID, field.TypeInt))
	if ps := wd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, wd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	wd.mutation.done = true
	return affected, err
}

// WithdrawalsDeleteOne is the builder for deleting a single Withdrawals entity.
type WithdrawalsDeleteOne struct {
	wd *WithdrawalsDelete
}

// Where appends a list predicates to the WithdrawalsDelete builder.
func (wdo *WithdrawalsDeleteOne) Where(ps ...predicate.Withdrawals) *WithdrawalsDeleteOne {
	wdo.wd.mutation.Where(ps...)
	return wdo
}

// Exec executes the deletion query.
func (wdo *WithdrawalsDeleteOne) Exec(ctx context.Context) error {
	n, err := wdo.wd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{withdrawals.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (wdo *WithdrawalsDeleteOne) ExecX(ctx context.Context) {
	if err := wdo.Exec(ctx); err != nil {
		panic(err)
	}
}
